### ISSUE TITLE
rHandler.exe flagged as trojanz

### ISSUE THREAD

**Issue by TimOverboard** [ahkscript/ASPDM#25]
I did have a quick look through the issues and nothing caught my eye, but I'll be surprised if this has not been raised before..
![image](https://user-images.githubusercontent.com/13855869/65628639-c6e7a080-dfc9-11e9-8ea0-47d5d929c173.png)

Obviously, my ASPDM client couldn't talk to anything after this..  might make me think the repos were offline, if I hadn't just used them :)

It's not unsual for windows to turn supernanny when faced with user-built exe files... I'm assuming this is the case here? Anyway.. maybe a warning and workaround somewhere might be nice. I don't think anyone installing this is will be affected by seeing the message. Just means I've gotta go into **settings** sigh. My god, I hate it.

btw the install is in my $home cos I wanted to see how it did it before installing into system.. dunno if it makes any difference to windows antivirus.

**Comment by joedf** [comment]
[rHandler.ahk](https://github.com/ahkscript/ASPDM/blob/master/Local-Client/rHandler.ahk)'s source code is available [here](https://github.com/ahkscript/ASPDM/blob/master/Local-Client/rHandler.ahk). You can compile it yourself and replace the one included with the installation. The above message is a false positive.

rHandler.exe is used for opening `*.ahkp` files and `ahkp://url-links`. This should be an exe, because of these functionalities are implemented in MS Windows.
